# Generated by Django 3.0.7 on 2020-06-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('categories', models.CharField(choices=[('phones', 'Phones nad Tablets'), ('computers', 'Computers and Accessories'), ('cars', 'Cars'), ('home', 'Home and Kicthen'), ('babies', 'Kids and Toys'), ('electronic', 'Electronics')], default=('phones', 'Phones nad Tablets'), max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('boosted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ad')),
            ],
        ),
    ]
