# Generated by Django 3.0.7 on 2020-07-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='categories',
            field=models.CharField(choices=[('phones', 'Phones and Tablets'), ('computers', 'Computers and Accessories'), ('cars', 'Cars'), ('home', 'Home and Kicthen'), ('babies', 'Kids and Toys'), ('electronic', 'Electronics')], default=('phones', 'Phones and Tablets'), max_length=300),
        ),
    ]
