# Generated by Django 3.0.7 on 2020-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200708_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.CharField(default='Ilaro Ogun State', max_length=100),
        ),
    ]
