# Generated by Django 3.0.7 on 2020-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200710_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
