# Generated by Django 3.0.7 on 2020-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200710_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
