# Generated by Django 3.0.7 on 2020-07-10 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_forumpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(primary_key=True,
                                        default=uuid.uuid4, editable=False)),
                ('comment', models.CharField(max_length=1200)),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='main.ForumPost')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
