# Generated by Django 3.0.7 on 2020-07-12 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_comment_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=1500)),
                ('job', models.CharField(max_length=60)),
                ('rating', models.PositiveIntegerField()),
                ('facebook', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Artisan')),
            ],
        ),
    ]
