# Generated by Django 3.0.7 on 2020-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_artisan_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='github',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='rating',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
