# Generated by Django 3.0.7 on 2020-07-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200712_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='facebook',
            field=models.URLField(max_length=50),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='github',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
