# Generated by Django 3.1.2 on 2020-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_forumpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='categories',
            field=models.CharField(choices=[('phones', 'Phones and Tablets'), ('computers', 'Computers and Accessories'), ('cars', 'Cars'), ('home', 'Home and Kicthen'), ('babies', 'Kids and Toys'), ('electronic', 'Electronics')], max_length=300),
        ),
    ]
