# Generated by Django 3.1.2 on 2020-10-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='address',
            field=models.CharField(default='Ilaro Ogun State', max_length=150),
        ),
    ]
