# Generated by Django 3.1.2 on 2020-10-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201019_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='long',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
