# Generated by Django 3.0.7 on 2020-06-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_artisan',
            field=models.BooleanField(default=False),
        ),
    ]
