# Generated by Django 3.1.2 on 2020-10-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0003_auto_20201008_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
